### PR TITLE
3 things lol

### PR DESCRIPTION
**Pull request by Steffan153**
So first, I fixed the bug where the theme wouldn't switch back to default.

As far as how I figured it out... First, look at this:
Screenshot_20201016_120623

The error basically just means that the theme `none` doesn't exist.

To figure out the right theme, I just started looking in your `e` object, and discovered a `getTheme` method. (of course I had to reload the page first)
Screenshot_20201016_120704

And that's the default theme.

Also, I scoped the preview next to the editor so it won't modify anything (using `iframe` and its `srcdoc`), before, if you stuck something like `<style>div { background: red; }</style>`, the entire thing would look nasty. Also, JS wouldn't work (because of XSS attack prevention).

One last thing, the live preview now live updates, without backend. Remember, if you open a window programatically you have control of everything.

Also, I'm just saying, this seems like a pretty cool project! :+1:

### CODE REVIEW

**Comment by Conner1115** [comment]
Wow!  Thanks, man.  I think I'll just merge the first pull request because Khan Academy doesn't want people to use <iframe> tags.

Thank you so much for helping me.

**Comment by Steffan153** [comment]
I think the iframe is fine, because it's not linking anywhere, just setting a `srcdoc`. Also in KA I've even tested that it works.

**Comment by Steffan153** [comment]
It's also possible to hijack it but that's probably against the Guidelines. You could ask a guardian I suppose.
```javascript
<script>
  var i = document.createElement('iframe');
  i.srcdoc = '<p>Hello!</p>';
  document.body.appendChild(i);
</script>
```

**Comment by Steffan153** [comment]
But the thing is, without an iframe, you won't even be able to do JS without really hijacking (if you use innerHTML). It's just a browser prevention of XSS attacks.
Also, you're gonna have to be really careful with CSS...

**Comment by Steffan153** [comment]
Nevermind, if I use the shadow root it should work fine! Let me try

**Pull request merged**
